### ISSUE TITLE
AttributeError when try to create new client

### ISSUE THREAD

**Issue by Furkan125** [kaJob-dev/growtopia.py#11]
Hello. I was trying to create a client and I am getting this error:

`Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    client = growtopia.Client()
  File "C:\Users\Furkan\AppData\Local\Programs\Python\Python311\Lib\site-packages\growtopia\client.py", line 27, in __init__
    self.checksum = enet.ENET_CRC32
AttributeError: module 'enet' has no attribute 'ENET_CRC32'`

**Comment by kaJob-dev** [comment]
How did you install growtopia.py?

**Comment by Furkan125** [comment]
so I shouldn't download pyenet with pip right?

**Comment by kaJob-dev** [comment]
Yes, that's the issue. Pip does not support direct dependencies, as said in the readme.md file. You'd have to install PyENet separately.

**Comment by Furkan125** [comment]
Ok, I fixed the problem. Thanks.
