### ISSUE TITLE
Question about examples

### ISSUE THREAD

**Issue by Furkan125** [kaJob-dev/growtopia.py#12]
I tried to run the simple_example server to understand the module better. I added 127.0.0.1 growtopia1.com to the hosts file and started the server and also the client, but when I connect to the game, I can't see any message on the python screen. What could I be doing wrong?

**Comment by kaJob-dev** [comment]
The client is probably not being redirected to the game server. Do you have a web server running on port 443?

**Comment by Furkan125** [comment]
No I don't have

**Comment by kaJob-dev** [comment]
You need to have one in order to redirect the client to the game server. You can probably look at the flask framework to get one running in python.

**Comment by Furkan125** [comment]
Ok I'll try.

**Comment by kaJob-dev** [comment]
I'll close this issue now. You may seek for help in the discord server, I'd be more than happy to help you there. Thanks.
