### ISSUE TITLE
Function to get the players from the player pool

### ISSUE THREAD

**Issue by Zoxorer** [kaJob-dev/growtopia.py#13]
I'm using player pool to hold connected players but I need a function to get all players in player pool

https://github.com/kaJob-dev/growtopia.py/blob/9e1b4933115a4a1d10aaf3617c6e52e7f8c7bc0c/growtopia/player_pool.py#L12

Of course I can't access the attribute because it's private
I need a function like this
```python
def get_players(self):
    return self.__players
```

**Comment by kaJob-dev** [comment]
Hello, thank you so much for pointing this out and creating a pr. I'll continue talking to you regarding this in the PR you opened.
