### ISSUE TITLE
Growtopia Buttons

### ISSUE THREAD

**Issue by galeryixone** [kaJob-dev/growtopia.py#4]
How to use add_text_input , or etc ?

**Comment by galeryixone** [comment]
How can we use the functions add_text_input| and add_textbox| to create a dialog box where users can input text? And once the user has submitted the text, how can we process that value?

**Comment by galeryixone** [comment]
In [Basic DIalog Support](https://github.com/kaJob-dev/growtopia.py/pull/6) In the example provided, when we send a dialog and use the 'add_button' , how can we add another dialog for the button, like chose language?

**Comment by kaJob-dev** [comment]
For that, you'd need to handle the ``dialog_return`` packet. You can either handle it in ``ON_RECEIVE``, or you could wait until I've implemented dialog handling.

**Comment by galeryixone** [comment]
can give some example?

**Comment by kaJob-dev** [comment]
Let's say the dialog we sent is as follows:
```py
welcome = Dialog()
welcome.add_textbox("Welcome to the server!")
welcome.add_checkbox("news_checkbox", "Recieive news?", False)
welcome.add_button("ok", "Ok")
welcome.add_ending("test_dialog", "Back", "Enter")

# add_textbox|Welcome to the server!|left|\nadd_checkbox|news_checkbox|Recieive news?|0|\nadd_button|ok|Ok|noflags|0|0|\nend_dialog|test_dialog|Back|Enter|\n
```

You'd handle the dialog_return packet in the ON_UNHANDLED event listener. You'd want to do something similar to the following:
```py
@server.listener
async def on_unhandled(ctx: Context):
    if ctx.packet.type == PacketType.TEXT:
        if "action" in ctx.packet.kvps and ctx.packet.kvps["action"] == "dialog_return":
            dialog_name = ctx.packet.kvps["dialog_name"]
            button_clicked = ctx.packet.kvps[
                "buttonClicked"
            ]  # This will not work if the button clicked is an ending button. (i.e specified in add_ending())
            checkbox_state = ctx.packet.kvps["news_checkbox"]

            print(dialog_name, button_clicked, checkbox_state) # output: test_dialog ok 1
```
Not really neat at all, though it works for now, and only in the v0.1.2 branch. I'm working on implementing listeners for the Dialog class to make it much easier and a ton more convenient to handle dialogs.
